In [ ]:
# numpy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.
import numpy as np
arr1=np.array([1, 2, 3, 4, 5])
print(arr1)
print(type(arr1))
arr1 = arr1.reshape(1,5)
print(arr1)
# convert 1D array to 2D array

[1 2 3 4 5]
<class 'numpy.ndarray'>
[[1 2 3 4 5]]


In [ ]:
arr2=np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)
print(type(arr2))
# two dimensional array

[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>


In [ ]:
arr1=np.arange(0, 10, 2)
arr1
arr1.reshape(5,1)


array([[0],
       [2],
       [4],
       [6],
       [8]])

In [11]:
# a two dimensional array with 3 rows and 4 columns with all values as 1
# np.ones((3,4))
# identity matrix of 3x3
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# printing 5,6,8,9 from 2D array
arr3=np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr3[1:,1:3])
# we can access the elements in 2D array using slicing. Here we are printing the elements from 1st row and 1st column to 2nd row and 2nd column.
arr3[0][0]=100
print(arr3)

[[5 6]
 [8 9]]
[[100   2   3]
 [  4   5   6]
 [  7   8   9]]


In [ ]:
#normailization of array
arr=np.array([1,2,3,4,5])
print(type(arr))
arr.ndim


<class 'numpy.ndarray'>


1

In [20]:
# Normalization of array is nothing but the mean is zero and the standard deviation is 1. It is also called as standardization of array. The formula for normalization is (x-mean)/standard deviation. Here x is the value of the array, mean is the mean of the array and standard deviation is the standard deviation of the array.
data=np.array([1,2,3,4,5])
mean=np.mean(data)
standard_deviation=np.std(data)
normalized_data=(data-mean)/standard_deviation
print(normalized_data)
# some other operations on array are median and variance. The median is the middle value of the array and the variance is the measure of how far the values in the array are from the mean. The formula for variance is (sum of (x-mean)^2)/n where x is the value of the array, mean is the mean of the array and n is the number of values in the array.
median=np.median(data)
variance=np.var(data)
print(median)
print(variance)
data[data>3]

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]
3.0
2.0


array([4, 5])

In [7]:
import numpy as np
# take a 5x5 array with 1-20 numbers
arr=np.random.randint(1,20,(5,5))

arr
arr[0:,3]


array([ 8,  2, 13,  6,  4], dtype=int32)

In [15]:
arr1=np.array([[1,2,3],[4,5,6],[7,8,9]])
arr1
mean=np.mean(arr1)
standard_deviation=np.std(arr1)
normalized_data=(arr1-mean)/standard_deviation
normalized_data

array([[-1.54919334, -1.161895  , -0.77459667],
       [-0.38729833,  0.        ,  0.38729833],
       [ 0.77459667,  1.161895  ,  1.54919334]])

In [9]:
# create a numpy array with shape(5,5)
arr=np.arange(1,10).reshape(3,3)
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])